<a href="https://colab.research.google.com/github/jsuryakt/ML_Practice_models/blob/master/Liver-Problem-Logistic-Model/Liver_Problem_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
liver_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/liver_patient_data/indian_liver_patient_dataset.csv')

In [3]:
liver_data.head(10)

Age  Gender  ...  Albumin_and_Globulin_Ratio  Liver_Problem
0   65  Female  ...                        0.90              1
1   62    Male  ...                        0.74              1
2   62    Male  ...                        0.89              1
3   58    Male  ...                        1.00              1
4   72    Male  ...                        0.40              1
5   46    Male  ...                        1.30              1
6   26  Female  ...                        1.00              1
7   29  Female  ...                        1.10              1
8   17    Male  ...                        1.20              2
9   55    Male  ...                        1.00              1

[10 rows x 11 columns]

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import warnings

In [5]:
warnings.filterwarnings("ignore")

In [22]:
liver_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         500 non-null    int64  
 1   Gender                      500 non-null    object 
 2   Total_Bilirubin             500 non-null    float64
 3   Direct_Bilirubin            500 non-null    float64
 4   Alkaline_Phosphotase        500 non-null    int64  
 5   Alamine_Aminotransferase    500 non-null    int64  
 6   Aspartate_Aminotransferase  500 non-null    int64  
 7   Total_Protiens              500 non-null    float64
 8   Albumin                     500 non-null    float64
 9   Albumin_and_Globulin_Ratio  500 non-null    float64
 10  Liver_Problem               500 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 43.1+ KB


In [9]:
liver_data.shape

(500, 11)

In [11]:
liver_data["Liver_Problem"].value_counts()

1    350
2    150
Name: Liver_Problem, dtype: int64

In [21]:
liver_data[liver_data["Albumin_and_Globulin_Ratio"].isnull()]

Empty DataFrame
Columns: [Age, Gender, Total_Bilirubin, Direct_Bilirubin, Alkaline_Phosphotase, Alamine_Aminotransferase, Aspartate_Aminotransferase, Total_Protiens, Albumin, Albumin_and_Globulin_Ratio, Liver_Problem]
Index: []

In [20]:
liver_data.Albumin_and_Globulin_Ratio.fillna(liver_data["Albumin_and_Globulin_Ratio"].mean(), inplace= True)

In [23]:
liver_data["Albumin_and_Globulin_Ratio"].mean()

0.9609072580645165

In [28]:
liver_data["Gender"] = liver_data.Gender.apply(lambda x: 1 if x == "Male" else 0)

In [29]:
liver_data.Gender

0      0
1      1
2      1
3      1
4      1
      ..
495    1
496    1
497    1
498    1
499    1
Name: Gender, Length: 500, dtype: int64

In [30]:
X = liver_data.drop("Liver_Problem", axis = 1)

In [31]:
y = liver_data["Liver_Problem"]

In [32]:
X

Age  Gender  ...  Albumin  Albumin_and_Globulin_Ratio
0     65       0  ...      3.3                        0.90
1     62       1  ...      3.2                        0.74
2     62       1  ...      3.3                        0.89
3     58       1  ...      3.4                        1.00
4     72       1  ...      2.4                        0.40
..   ...     ...  ...      ...                         ...
495   32       1  ...      3.0                        0.96
496   24       1  ...      4.8                        1.50
497   67       1  ...      3.0                        0.70
498   68       1  ...      4.0                        1.60
499   55       1  ...      2.9                        0.60

[500 rows x 10 columns]

In [33]:
y

0      1
1      1
2      1
3      1
4      1
      ..
495    2
496    1
497    1
498    1
499    1
Name: Liver_Problem, Length: 500, dtype: int64

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [103]:
model = LogisticRegression()

In [104]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [105]:
pred = model.predict(X_test)

In [106]:
from sklearn.metrics import accuracy_score
accuracy_score(pred, y_test)

0.61

In [48]:
test_new = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/liver_patient_data/indian_liver_patient_new_testdataset.csv')

In [ ]:
test_new.head()

In [50]:
test_new["Gender"] = test_new.Gender.apply(lambda x: 1 if x == "Male" else 0)

In [52]:
test_new.head(10)

Age  Gender  ...  Albumin  Albumin_and_Globulin_Ratio
0   36       1  ...      2.5                         0.7
1   42       1  ...      2.7                         1.2
2   53       1  ...      2.5                         0.4
3   32       1  ...      2.7                         0.9
4   32       1  ...      3.1                         1.1
5   56       1  ...      2.4                         0.7
6   50       1  ...      3.9                         1.0
7   46       1  ...      3.3                         0.7
8   46       1  ...      3.0                         1.2
9   37       0  ...      4.6                         1.0

[10 rows x 10 columns]

In [54]:
test_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         82 non-null     int64  
 1   Gender                      82 non-null     int64  
 2   Total_Bilirubin             82 non-null     float64
 3   Direct_Bilirubin            82 non-null     float64
 4   Alkaline_Phosphotase        82 non-null     int64  
 5   Alamine_Aminotransferase    82 non-null     int64  
 6   Aspartate_Aminotransferase  82 non-null     int64  
 7   Total_Protiens              82 non-null     float64
 8   Albumin                     82 non-null     float64
 9   Albumin_and_Globulin_Ratio  82 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 6.5 KB


In [73]:
Liver_Problem = model.predict(test_new)

In [74]:
Liver_Problem

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [60]:
Liver_Problem = model.predict(test_new)

In [107]:
full_train_model = LogisticRegression()
full_train_model.fit(X,y)
full_train_solution = full_train_model.predict(test_new)

In [111]:
full_train_solution 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [112]:
Liver_Problem

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [126]:
res = pd.DataFrame(Liver_Problem)
res.index = test_new.index
res.to_csv("Liver_Problem_Solution_test.txt", index= False, line_terminator=',')

In [125]:
ans_1 = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2]
print(len(ans_1))

82
